export default {
  FeatureName: 'Pricelists Tests',
  features: [
    {
      tcid: '1',
      name: '@pricelist-validation-filter-combination-one',
      path: '/na/channelpartners/?georouting=off&martech=off',
      tags: '@dme-pricelists @regression @circleCi',
      data: {
        partnerLevel: 'cpp-distributor-all:',
        signInButtonInternationalText: 'Sign In',
        usdCheckBox: 'USD',
        vipCommercialCheckBox: 'VIP Commercial',
        asiaPacificCheckBox: 'Asia Pacific',
        expectedURL: '/na/channelpartners/#',
      },
    },
    {
      tcid: '2',
      name: '@pricelist-validation-filter-combination-two',
      path: '/na/channelpartners/?georouting=off&martech=off',
      tags: '@dme-pricelists @regression @circleCi',
      data: {
        partnerLevel: 'cpp-distributor-all:',
        signInButtonInternationalText: 'Sign In',
        jpyCheckBox: 'JPY',
        ycVipCommercialCheckBox: '3YC VIP MP Commercial',
        japanCheckBox: 'Japan',
        worldwide: 'Worldwide',
        expectedURL: '/na/channelpartners/#',
      },
    },
    {
      tcid: '3',
      name: '@pricelist-validation-filter-combination-three',
      path: '/na/channelpartners/?georouting=off&martech=off',
      tags: '@dme-pricelists @regression @circleCi',
      data: {
        partnerLevel: 'cpp-distributor-all:',
        signInButtonInternationalText: 'Sign In',
        keyword: 'Korea',
        asiaPacificKorea: 'Asia Pacific,Korea',
        tlp5CommercialCheckBox: 'TLP 5 Commercial',
        europeEastCheckBox: 'Europe East',
        expectedURL: '/na/channelpartners/#',
      },
    },
    {
      tcid: '4',
      name: '@pricelist-validation-filter-combination-four',
      path: '/na/channelpartners/?georouting=off&martech=off',
      tags: '@dme-pricelists @regression @circleCi',
      data: {
        partnerLevel: 'cpp-distributor-all:',
        signInButtonInternationalText: 'Sign In',
        pacificCheckBox: 'Pacific',
        audCheckBox: 'AUD',
        vipCommercialCheckBox: 'VIP Commercial',
        expectedURL: '/na/channelpartners/#',
      },
    },
    {
      tcid: '5',
      name: '@pricelist-validation-platinum-user',
      path: '/na/channelpartners/?georouting=off&martech=off',
      tags: '@dme-pricelists @regression @circleCi',
      data: {
        partnerLevel: 'cpp-platinum-all:',
        europeEast: 'Europe East',
        europeWest: 'Europe West',
        worldwide: 'Worldwide',
        northAmerica: 'North America',
      },
    },
    {
      tcid: '6',
      name: '@pricelist-validation-gold-user',
      path: '/na/channelpartners/?georouting=off&martech=off',
      tags: '@dme-pricelists @regression @circleCi',
      data: {
        partnerLevel: 'cpp-gold-all:',
        europeEast: 'Europe East',
        europeWest: 'Europe West',
        northAmerica: 'North America',
      },
    },
    {
      tcid: '7',
      name: '@pricelist-validation-certified-user',
      path: '/na/channelpartners/?georouting=off&martech=off',
      tags: '@dme-pricelists @regression @circleCi',
      data: {
        partnerLevel: 'cpp-certified-all:',
        europeEast: 'Europe East',
        europeWest: 'Europe West',
        northAmerica: 'North America',
      },
    },
    {
      tcid: '8',
      name: '@pricelist-validation-registered-user',
      path: '/na/channelpartners/?georouting=off&martech=off',
      tags: '@dme-pricelists @regression @circleCi',
      data: { partnerLevel: 'cpp-registered-all:' },
    },
    {
      tcid: '9',
      name: '@pricelist-validation-distributor-india-user',
      path: '/na/channelpartners/?georouting=off&martech=off',
      tags: '@dme-pricelists @regression @circleCi',
      data: {
        partnerLevel: 'cpp-distributor-india:',
        text: 'Asia Pacific,Korea',
      },
    },
    {
      tcid: '10',
      name: '@pricelist-validation-kr-distributor-user',
      path: '/na/channelpartners/?georouting=off&martech=off',
      tags: '@dme-pricelists @regression @circleCi',
      data: {
        partnerLevel: 'cpp-kr-distributor:',
        text: 'Asia Pacific,Korea',
      },
    },
    {
      tcid: '11',
      name: '@pricelist-validation-cpp-distr-latin-america-na-user',
      path: '/na/channelpartners/?georouting=off&martech=off',
      tags: '@dme-pricelists @regression @circleCi',
      data: {
        partnerLevel: 'cpp-latin-na-platinum:',
        checkBox: 'Latin America (NA based)',
        text: 'Latin America (NA based)',
      },
    },
    {
      tcid: '12',
      name: '@pricelist-validation-cpp-distributor-us-user',
      path: '/na/channelpartners/?georouting=off&martech=off',
      tags: '@dme-pricelists @regression @circleCi',
      data: {
        partnerLevel: 'cpp-distributor-us:',
        checkBox: 'North America',
        text: 'North America',
      },
    },
  ],
};
