export default {
  FeatureName: 'DME redirects flow',
  features: [
    {
      tcid: '1',
      name: '@redirects-for-na-locale',
      path: '/na/channelpartners/drafts/automation/regression/redirects/redirects-test?georouting=off&martech=off',
      tags: '@dme-redirects @regression @anonymous @dme-main',
      data: {
        partnerLevel: 'cpp-distributor-us:',
        partnerData: {
          partnerPortal: 'CPP',
          partnerLevel: 'Distributor',
          permissionRegion: 'North America',
        },
        cbcEnablementLabel: 'cbconnection.adobe.com/en/news/enablement-news-partner-lock',
        cbcEnablementLink: '/en/news/enablement-news-partner-lock',
        cbcEnablementLinkSignInUser: '/bin/fusion/modalImsLogin?resource=%2Fen%2Fnews%2Fenablement-news-partner-lock',
        helpXAdobeLink: 'https://helpx.adobe.com/',
        salesCenterMainLink: 'https://channelpartners.adobe.com/s/salescenter/dashboard',
        salesCenterLink: '/s/salescenter/dashboard',
        adobeLink: 'https://www.adobe.com/',
        businessAdobeLink: 'https://business.adobe.com/',
      },
    },
    {
      tcid: '2',
      name: '@redirects-for-emea-locale',
      path: '/emea/channelpartners/drafts/automation/regression/redirects/redirects-test?georouting=off&martech=off',
      tags: '@dme-redirects @regression @anonymous @dme-main',
      data: {
        partnerLevel: 'cpp-europe-east-certified:',
        partnerData: {
          partnerPortal: 'CPP',
          partnerLevel: 'Certified',
          permissionRegion: 'Europe East',
        },
        cbcEnablementLabel: 'cbconnection.adobe.com/en/news/enablement-news-partner-lock',
        cbcEnablementLink: '/en/news/enablement-news-partner-lock',
        cbcEnablementLinkSignInUser: '/bin/fusion/modalImsLogin?resource=%2Fen%2Fnews%2Fenablement-news-partner-lock',
        helpXAdobeLink: 'https://helpx.adobe.com/uk/',
        salesCenterMainLink: '/s/salescenter/dashboard',
        salesCenterLink: '/s/salescenter/dashboard',
        adobeLink: 'https://www.adobe.com/uk/',
        businessAdobeLink: 'https://business.adobe.com/uk/',
      },
    },
    {
      tcid: '3',
      name: '@redirects-for-cn-locale',
      path: '/cn/channelpartners/drafts/automation/regression/redirects/redirects-test?georouting=off&martech=off',
      tags: '@dme-redirects @regression @anonymous @dme-main',
      data: {
        partnerLevel: 'cpp-china-registered:',
        partnerData: {
          partnerPortal: 'CPP',
          partnerLevel: 'Registered',
          permissionRegion: 'China',
        },
        cbcEnablementLabel: 'cbconnection.adobe.com/en/news/enablement-news-partner-lock',
        cbcEnablementLink: '/zh_cn/news/enablement-news-partner-lock',
        cbcEnablementLinkSignInUser: '/bin/fusion/modalImsLogin?resource=%2Fzh_cn%2Fnews%2Fenablement-news-partner-lock',
        helpXAdobeLink: 'https://helpx.adobe.com/cn/',
        salesCenterMainLink: '/s/salescenter/dashboard',
        salesCenterLink: '/s/salescenter/dashboard',
        adobeLink: 'https://www.adobe.com/cn/',
        businessAdobeLink: 'https://business.adobe.com/cn/',
      },
    },
  ],
};
