export default {
  FeatureName: 'DME Announcements Preview',
  features: [
    {
      tcid: '1',
      name: '@desc-regression-announcements-preview-platinum-user',
      path: '/channelpartners/?georouting=off&martech=off',
      tags: '@dme-announcements-preview @regression @circleCi',
      data: {
        partnerLevel: 'cpp-spain-platinum:',
        signInButton: 'Sign In',
        expectedProtectedHomeURL: '/channelpartners/home/',
        selectedSortNewest: 'Date: newest',
        rootPath: '/channelpartners/',
      },
    },
    {
      tcid: '2',
      name: '@desc-regression-announcements-preview-registered-user',
      path: '/channelpartners/?georouting=off&martech=off',
      tags: '@dme-announcements-preview @regression @circleCi',
      data: {
        partnerLevel: 'cpp-china-registered:',
        signInButton: 'Sign In',
        expectedProtectedHomeURL: '/channelpartners/home/',
        selectedSortNewest: 'Date: newest',
        rootPath: '/channelpartners/',
      },
    },
    {
      tcid: '3',
      name: '@desc-regression-announcements-preview-gold-user',
      path: '/channelpartners/?georouting=off&martech=off',
      tags: '@dme-announcements-preview @regression @circleCi',
      data: {
        partnerLevel: 'cpp-latin-america-gold:',
        signInButton: 'Sign In',
        expectedProtectedHomeURL: '/channelpartners/home/',
        selectedSortNewest: 'Date: newest',
        rootPath: '/channelpartners/',
      },
    },
    {
      tcid: '4',
      name: '@desc-regression-announcements-preview-certified-user',
      path: '/channelpartners/?georouting=off&martech=off',
      tags: '@dme-announcements-preview @regression @circleCi',
      data: {
        partnerLevel: 'cpp-europe-east-certified:',
        signInButton: 'Sign In',
        expectedProtectedHomeURL: '/channelpartners/home/',
        selectedSortNewest: 'Date: newest',
        rootPath: '/channelpartners/',
      },
    },
    {
      tcid: '5',
      name: '@desc-regression-announcements-preview-distributor-user',
      path: '/channelpartners/?georouting=off&martech=off',
      tags: '@dme-announcements-preview @regression @circleCi',
      data: {
        partnerLevel: 'cpp-distributor-us:',
        signInButton: 'Sign In',
        expectedProtectedHomeURL: '/channelpartners/home/',
        selectedSortNewest: 'Date: newest',
        rootPath: '/channelpartners/',
      },
    },
  ],
};
