export default {
  FeatureName: 'DME Protected Content Access',
  features: [
    {
      tcid: '1',
      name: '@desc-accessing-protected-content-with-non-logged-in-user',
      path: '/channelpartners/drafts/automation/regression/cards/cpp-gold-spain?georouting=off&martech=off',
      tags: '@dme-protected-content @regression @login @circleCi',
      expectedToSeeInURL: 'https://auth-stg1.services.adobe.com/',
    },
    {
      tcid: '2',
      name: '@desc-accessing-protected-content-with-logged-in-non-member-user',
      path: '/channelpartners/drafts/automation/regression/public-page?georouting=off&martech=off',
      tags: '@dme-protected-content @regression @login @circleCi',
      data: {
        partnerLevel: 'dxp-platinum:',
        contactNotFoundPage: '/error/contact-not-found',
        contentNotFoundPagePlatinum: 'https://partners.stage.adobe.com/channelpartners/drafts/automation/regression/cards/cpp-platinum-spain?georouting=off&martech=off',
        contentNotFoundPageGold: 'https://partners.stage.adobe.com/channelpartners/drafts/automation/regression/cards/cpp-gold-spain?georouting=off&martech=off',
        goldLevelPage: 'https://partners.stage.adobe.com/channelpartners/drafts/automation/regression/cards/cpp-gold-spain?georouting=off&martech=off',
        platinumLevelPage: 'https://partners.stage.adobe.com/channelpartners/drafts/automation/regression/cards/cpp-platinum-spain?georouting=off&martech=off',
      },
    },
    {
      tcid: '3',
      name: '@desc-accessing-protected-content-with-logged-in-member-user-distributor-level',
      path: '/channelpartners/drafts/automation/regression/public-page?georouting=off&martech=off',
      tags: '@dme-protected-content @regression @login @circleCi',
      data: {
        partnerLevel: 'cpp-distributor-japan:',
        matchingRegionPage: 'https://partners.stage.adobe.com/channelpartners/drafts/automation/regression/cards/cpp-distr-japan?georouting=off&martech=off',
        nonMatchingRegionPage: 'https://partners.stage.adobe.com/channelpartners/drafts/automation/regression/cards/cpp-distr-north-america',
        nonMatchingRegionPageDistr: 'https://partners.stage.adobe.com/jp/channelpartners/drafts/automation/regression/cards/cpp-distr-north-america',
        nonMatchingPartnerLevelPage: 'https://partners.stage.adobe.com/channelpartners/drafts/automation/regression/cards/cpp-platinum-spain',
        contentNotFoundPagePlatinum: 'https://partners.stage.adobe.com/jp/channelpartners/drafts/automation/regression/cards/cpp-platinum-spain',
      },
      matchingRegionCardText: 'CPP Distributor Japan Announcement',
      nonMatchingRegionCardText: 'CPP Distributor North America Announcement',
    },
    {
      tcid: '4',
      name: '@desc-accessing-protected-content-with-logged-in-member-user-platinum-level',
      path: '/channelpartners/drafts/automation/regression/public-page?georouting=off&martech=off',
      tags: '@dme-protected-content @regression @login @circleCi',
      data: {
        partnerLevel: 'cpp-spain-platinum:',
        contentNotFoundPage: 'https://partners.stage.adobe.com/es/channelpartners/drafts/automation/regression/cards/cpp-gold-anuncio-de-espana?georouting=off&martech=off',
        matchingRegionPage: 'https://partners.stage.adobe.com/es/channelpartners/drafts/automation/regression/cards/cpp-platinum-anuncio-de-espana?georouting=off&martech=off',
        nonMatchingPartnerLevelPage: 'https://partners.stage.adobe.com/es/channelpartners/drafts/automation/regression/cards/cpp-gold-anuncio-de-espana?georouting=off&martech=off',
      },
      matchingRegionCardText: 'CPP Platinum Anuncio de España',
    },
    {
      tcid: '5',
      name: '@desc-accessing-protected-content-with-logged-in-member-user-gold-level',
      path: '/channelpartners/drafts/automation/regression/public-page?georouting=off&martech=off',
      tags: '@dme-protected-content @regression @login @circleCi',
      data: {
        partnerLevel: 'cpp-uk-gold:',
        contentNotFoundPage: 'https://partners.stage.adobe.com/emea/channelpartners/drafts/automation/regression/cards/cpp-certified-emea?georouting=off&martech=off',
        matchingRegionPage: 'https://partners.stage.adobe.com/emea/channelpartners/drafts/automation/regression/cards/cpp-gold-emea-uk-eur-west?georouting=off&martech=off',
        nonMatchingPartnerLevelPage: 'https://partners.stage.adobe.com/emea/channelpartners/drafts/automation/regression/cards/cpp-certified-emea?georouting=off&martech=off',
      },
      matchingRegionCardText: 'CPP Gold EMEA UK, Europe West Announcement',
    },
    {
      tcid: '6',
      name: '@desc-accessing-protected-content-with-logged-in-member-user-certified-level',
      path: '/channelpartners/drafts/automation/regression/public-page?georouting=off&martech=off',
      tags: '@dme-protected-content @regression @login @circleCi',
      data: {
        partnerLevel: 'cpp-pacific-certified:',
        contentNotFoundPage: 'https://partners.stage.adobe.com/apac/channelpartners/drafts/automation/regression/cards/cpp-gold-pacific?georouting=off&martech=off',
        matchingRegionPage: 'https://partners.stage.adobe.com/apac/channelpartners/drafts/automation/regression/cards/cpp-certified-pacific?georouting=off&martech=off',
        nonMatchingPartnerLevelPage: 'https://partners.stage.adobe.com/apac/channelpartners/drafts/automation/regression/cards/cpp-gold-pacific?georouting=off&martech=off',
      },
      matchingRegionCardText: 'CPP Certified APAC Announcement',
    },
    {
      tcid: '7',
      name: '@desc-accessing-protected-content-with-logged-in-member-user-registered-level',
      path: '/channelpartners/drafts/automation/regression/public-page?georouting=off&martech=off',
      tags: '@dme-protected-content @regression @login @circleCi',
      data: {
        partnerLevel: 'cpp-china-registered:',
        contentNotFoundPage: 'https://partners.stage.adobe.com/cn/channelpartners/drafts/automation/regression/cards/cpp-certified-china',
        matchingRegionPage: 'https://partners.stage.adobe.com/channelpartners/drafts/automation/regression/cards/cpp-registered-china?georouting=off&martech=off',
        nonMatchingPartnerLevelPage: 'https://partners.stage.adobe.com/channelpartners/drafts/automation/regression/cards/cpp-certified-china?georouting=off&martech=off',
      },
      matchingRegionCardText: 'APC Registered China Announcement',
    },
  ],
};
