export default {
  FeatureName: 'DME Protected Content Access',
  features: [
    {
      tcid: '1',
      name: '@desc-accessing-protected-content-with-non-logged-in-user',
      path: '/channelpartners/drafts/automation/regression/cards/cpp-gold-spain?akamaiLocale=na&martech=off',
      tags: '@dme-protected-content @regression @login @circleCi',
      expectedToSeeInURL: 'https://auth-stg1.services.adobe.com/',
    },
    {
      tcid: '2',
      name: '@desc-accessing-protected-content-with-logged-in-non-member-user',
      path: '/channelpartners/drafts/automation/regression/public-page?akamaiLocale=na&martech=off',
      tags: '@dme-protected-content @regression @login @circleCi',
      data: {
        partnerLevel: 'spp-platinum:',
        contactNotFoundPage: '/error/contact-not-found',
        contentNotFoundPage: '/error/404',
        goldLevelPage: 'https://partners.stage.adobe.com/channelpartners/drafts/automation/regression/cards/cpp-gold-spain?akamaiLocale=na&martech=off',
        platinumLevelPage: 'https://partners.stage.adobe.com/channelpartners/drafts/automation/regression/cards/cpp-platinum-spain?akamaiLocale=na&martech=off',
      },
    },
    {
      tcid: '3',
      name: '@desc-accessing-protected-content-with-logged-in-member-user-distributor-level',
      path: '/channelpartners/drafts/automation/regression/public-page?akamaiLocale=na&martech=off',
      tags: '@dme-protected-content @regression @login @circleCi',
      data: {
        partnerLevel: 'cpp-distributor-japan:',
        contentNotFoundPage: '/error/404',
        matchingRegionPage: 'https://partners.stage.adobe.com/channelpartners/drafts/automation/regression/cards/cpp-distr-japan?akamaiLocale=na&martech=off',
        nonMatchingRegionPage: 'https://partners.stage.adobe.com/channelpartners/drafts/automation/regression/cards/cpp-distr-north-america?akamaiLocale=na&martech=off',
        nonMatchingPartnerLevelPage: 'https://partners.stage.adobe.com/channelpartners/drafts/automation/regression/cards/cpp-platinum-spain',
      },
      matchingRegionCardText: 'CPP Distributor Japan Announcement',
      nonMatchingRegionCardText: 'CPP Distributor North America Announcement',
    },
    {
      tcid: '4',
      name: '@desc-accessing-protected-content-with-logged-in-member-user-platinum-level',
      path: '/channelpartners/drafts/automation/regression/public-page?akamaiLocale=na&martech=off',
      tags: '@dme-protected-content @regression @login @circleCi',
      data: {
        partnerLevel: 'cpp-spain-platinum:',
        contentNotFoundPage: '/error/404',
        matchingRegionPage: 'https://partners.stage.adobe.com/channelpartners/drafts/automation/regression/cards/cpp-platinum-spain?akamaiLocale=na&martech=off',
        nonMatchingRegionPage: 'https://partners.stage.adobe.com/channelpartners/drafts/automation/regression/cards/cpp-platinum-latin-america?akamaiLocale=na&martech=off',
        nonMatchingPartnerLevelPage: 'https://partners.stage.adobe.com/channelpartners/drafts/automation/regression/cards/cpp-gold-spain?akamaiLocale=na&martech=off',
      },
      matchingRegionCardText: 'CPP Platinum Spain Announcement',
      nonMatchingRegionCardText: 'CPP Platinum Latin America Announcement',
    },
    {
      tcid: '5',
      name: '@desc-accessing-protected-content-with-logged-in-member-user-gold-level',
      path: '/channelpartners/drafts/automation/regression/public-page?akamaiLocale=na&martech=off',
      tags: '@dme-protected-content @regression @login @circleCi',
      data: {
        partnerLevel: 'cpp-uk-gold:',
        contentNotFoundPage: '/error/404',
        matchingRegionPage: 'https://partners.stage.adobe.com/channelpartners/drafts/automation/regression/cards/cpp-gold-uk-eur-west?akamaiLocale=na&martech=off',
        nonMatchingRegionPage: 'https://partners.stage.adobe.com/channelpartners/drafts/automation/regression/cards/cpp-gold-spain?akamaiLocale=na&martech=off',
        nonMatchingPartnerLevelPage: 'https://partners.stage.adobe.com/channelpartners/drafts/automation/regression/cards/cpp-certified-china?akamaiLocale=na&martech=off',
      },
      matchingRegionCardText: 'CPP Gold UK, Europe West Announcement',
      nonMatchingRegionCardText: 'CPP Gold Spain Announcement',
    },
    {
      tcid: '6',
      name: '@desc-accessing-protected-content-with-logged-in-member-user-certified-level',
      path: '/channelpartners/drafts/automation/regression/public-page?akamaiLocale=na&martech=off',
      tags: '@dme-protected-content @regression @login @circleCi',
      data: {
        partnerLevel: 'cpp-pacific-certified:',
        contentNotFoundPage: '/error/404',
        matchingRegionPage: 'https://partners.stage.adobe.com/channelpartners/drafts/automation/regression/cards/cpp-certified-pacific?akamaiLocale=na&martech=off',
        nonMatchingRegionPage: 'https://partners.stage.adobe.com/channelpartners/drafts/automation/regression/cards/cpp-certified-china?akamaiLocale=na&martech=off',
        nonMatchingPartnerLevelPage: 'https://partners.stage.adobe.com/channelpartners/drafts/automation/regression/cards/cpp-gold-spain?akamaiLocale=na&martech=off',
      },
      matchingRegionCardText: 'CPP Certified Pacific Announcement',
      nonMatchingRegionCardText: 'CPP Certified China Announcement',
    },
    {
      tcid: '7',
      name: '@desc-accessing-protected-content-with-logged-in-member-user-registered-level',
      path: '/channelpartners/drafts/automation/regression/public-page?akamaiLocale=na&martech=off',
      tags: '@dme-protected-content @regression @login @circleCi',
      data: {
        partnerLevel: 'cpp-china-registered:',
        contentNotFoundPage: '/error/404',
        matchingRegionPage: 'https://partners.stage.adobe.com/channelpartners/drafts/automation/regression/cards/cpp-registered-china?akamaiLocale=na&martech=off',
        nonMatchingRegionPage: 'https://partners.stage.adobe.com/channelpartners/drafts/automation/regression/cards/cpp-registered-europe-east?akamaiLocale=na&martech=off',
        nonMatchingPartnerLevelPage: 'https://partners.stage.adobe.com/channelpartners/drafts/automation/regression/cards/cpp-certified-china?akamaiLocale=na&martech=off',
      },
      matchingRegionCardText: 'CPP Registered China Announcement',
      nonMatchingRegionCardText: 'CPP Registered Europe East Announcement',
    },
  ],
};
