export default {
  FeatureName: 'PRP Collection',
  features: [
    {
      tcid: '1',
      name: '@prp-collection-apac-campus-store',
      path: '/apac/channelpartners/drafts/automation/regression/prp-collections/new-specializations-automation?georouting=off&martech=off',
      tags: '@prp-collection-test @regression @circleCi',
      data: {
        partnerLevel: 'cpp-distributor-india:',
        goTo: '/apac/channelpartners/home/search/?term=specializationsautomation',
        title: 'Campus Store Automation',
      },
    },
    {
      tcid: '2',
      name: '@prp-collection-fr-comercial',
      path: '/fr/channelpartners/drafts/automation/regression/prp-collections/new-specializations-automation?georouting=off&martech=off',
      tags: '@prp-collection-test @regression @circleCi',
      data: {
        partnerLevel: 'cpp-eur-east-fr:',
        goTo: '/fr/channelpartners/home/search/?term=specializationsautomation',
        title: 'Commercial Automation',
      },
    },
    {
      tcid: '3',
      name: '@prp-collection-emea-online-retail',
      path: '/emea/channelpartners/drafts/automation/regression/prp-collections/new-specializations-automation?georouting=off&martech=off',
      tags: '@prp-collection-test @regression @circleCi',
      data: {
        partnerLevel: 'cpp-eurwest:',
        goTo: '/emea/channelpartners/home/search/?term=specializationsautomation',
        title: 'Online Retail Automation',
      },
    },
    {
      tcid: '4',
      name: '@prp-collection-na-retail',
      path: '/na/channelpartners/drafts/automation/regression/prp-collections/new-specializations-automation?georouting=off&martech=off',
      tags: '@prp-collection-test @regression @circleCi',
      data: {
        partnerLevel: 'cpp-na-certified:',
        goTo: '/na/channelpartners/home/search/?term=specializationsautomation',
        title: 'Retail Automation',
      },
    },
    {
      tcid: '5',
      name: '@prp-collection-apac-collection-basics',
      path: '/channelpartners/drafts/automation/regression/prp-collections/prp-collection-all-levels?georouting=off&martech=off',
      tags: '@prp-collection-test @regression @circleCi',
      data: {
        partnerLevel: 'cpp-distributor-india:',
        title1: 'PRP Worldwide PPTX',
        title2: 'PRP Pacific DOCX',
        title3: 'PRP APAC AI(Adobe Illustrator)',
        collectionTitle: 'PRP Collection Automation All Levels',
        text1: 'DETAIL OPTIONAL',
        text2: 'Lorem ipsum odor amet,',
        text3: 'Language(s): EN, ES, IT',
        text4: 'Files in this collection 3',
        expectedURL: '/apac/channelpartners/home/marketing/resources/',
      },
    },
    {
      tcid: '6',
      name: '@prp-collection-china-card-gating',
      path: '/cn/channelpartners/drafts/automation/regression/prp-collections/prp-collection-all-levels?georouting=off&martech=off',
      tags: '@prp-collection-test @regression @circleCi',
      data: {
        partnerLevel: 'cpp-regist-china:',
        title1: 'PRP China doc',
        date: '2026年6月10日',
        tag: '繁体中文',
        downloadBtn: '下载',
        format: 'doc',
      },
    },
    {
      tcid: '7',
      name: '@prp-collection-filtering-and-sorting',
      path: '/channelpartners/drafts/automation/regression/prp-collections/prp-collection-all-levels?georouting=off&martech=off',
      tags: '@prp-collection-test @regression @circleCi',
      data: {
        partnerLevel: 'cpp-uk-gold:',
        card1: 'PRP Worldwide PPTX',
        card2: 'PRP UK ZIP',
        card3: 'PRP Europe West JPEG',
        card4: 'PRP EMEA EPS',
        filter1: 'Language',
        filter2: 'Type',
        checkBox1: 'English Universal (EU)',
        checkBox2: 'Spanish',
        checkBox3: 'Advertising',
        sortNewest: 'Newest',
        sortOldest: 'Oldest',
      },
    },
    {
      tcid: '8',
      name: '@prp-collection-it-specialization-gate',
      path: '/channelpartners/drafts/automation/regression/prp-collections/prp-collection-all-levels?georouting=off&martech=off',
      tags: '@prp-collection-test @regression @circleCi',
      data: {
        partnerLevel: 'cpp-cert-it:',
        filter1: 'Tipo',
      },
    },
    {
      tcid: '9',
      name: '@prp-collection-da-collection-search-sink',
      path: '/channelpartners/drafts/automation/regression/prp-collections/prp-collection-all-levels?georouting=off&martech=off',
      tags: '@prp-collection-test @regression @circleCi',
      data: {
        partnerLevel: 'cpp-de-gold:',
        searchPageUrl: 'https://partners.stage.adobe.com/de/channelpartners/home/search/?term=prpautomation2026',
        title1: 'PRP Worldwide PPTX',
        title2: 'PRP Europe West JPEG',
        title3: 'PRP EMEA EPS',
        searchCardDate: '8. Juni 2026',
        searchCardSize: 'Größe: 28,2 kB',
      },
    },
    {
      tcid: '10',
      name: '@prp-collection-mea-tag-exclusion',
      path: '/channelpartners/drafts/automation/regression/prp-collections/prp-collection-all-levels?georouting=off&martech=off',
      tags: '@prp-collection-test @regression @circleCi',
      data: {
        partnerLevel: 'cpp-mid-east-africa-registered:',
        title1: 'PRP Middle East Africa JPG',
        tag: 'Collections',
      },
    },
    {
      tcid: '11',
      name: '@prp-collection-jp-locale-card-labels',
      path: '/channelpartners/drafts/automation/regression/prp-collections/prp-collection-all-levels?georouting=off&martech=off',
      tags: '@prp-collection-test @regression @circleCi',
      data: {
        partnerLevel: 'cpp-japan-distributor:',
        title1: 'PRP Worldwide PPTX',
        title2: 'PRP Japan XLSX',
        tag: ["メッセージングまたはポジショニング", "セールスガイド", "報告", "英語（ユニバーサル）（EU）"],
        cardDownloadBtn: 'ダウンロードする',
      },
    },
    {
      tcid: '12',
      name: '@prp-collection-kr-refresh-persistence',
      path: '/channelpartners/drafts/automation/regression/prp-collections/prp-collection-all-levels?georouting=off&martech=off',
      tags: '@prp-collection-test @regression @circleCi',
      data: {
        partnerLevel: 'cpp-platinum-kr:',
        title1: 'PRP Worldwide PPTX',
        title2: 'PRP APAC AI(Adobe Illustrator)',
      },
    },
    {
      tcid: '13',
      name: '@marketing-resources-apac-resource-load-more',
      path: '/channelpartners/drafts/automation/regression/resources?georouting=off&martech=off',
      tags: '@prp-collection-test @regression @circleCi',
      data: {
        partnerLevel: 'cpp-distributor-india:',
        searchKeyword: 'PRP Collection Automation',
        sortOption: 'Oldest',
        title1: 'PRP Collection Automation Distributor Platinum Gold',
        expectedURL: '/apac/channelpartners/drafts/automation/regression/prp-collections/prp-collection-distr-plat-gold',
      },
    },
    {
      tcid: '14',
      name: '@marketing-resources-na-filter-ditails',
      path: '/channelpartners/drafts/automation/regression/resources?georouting=off&martech=off',
      tags: '@prp-collection-test @regression @circleCi',
      data: {
        partnerLevel: 'cpp-na-certified:',
        searchKeyword: 'PRP Collection Automation',
        title1: 'PRP Collection Automation All Levels ',
        filter1: 'Product',
        checkBox1: 'Adobe Acrobat',
        title2: 'PRP Collection Automation Distributor Certified Registered ŴĦÐŒÞȲŁЖЮҐЩЙЋΨΩΔξβπηさツみロめ愛龍雪火星क्षज्ञअभऋङ한글ㅁㅊㅓㅂعضشقء ל זטכ',
        checkBox2: 'Adobe Connect',
        filter2: 'Topic',
        checkBox3: 'Onboarding',
        checkbox4: 'Program Guide',
      },
    },
    {
      tcid: '15',
      name: '@marketing-resources-de-resource-clear-filters',
      path: '/channelpartners/drafts/automation/regression/resources?georouting=off&martech=off',
      tags: '@prp-collection-test @regression @circleCi',
      data: {
        partnerLevel: 'cpp-de-gold:',
        searchKeyword: 'PRP Collection Automation',
        title1: 'PRP Collection Automation All Levels',
        title2: 'PRP Collection Automation Distributor Platin Gold',
        title3: 'PRP Collection Automation Gold Certified Registered',
        filter1: 'Produkt',
        filter2: 'Thema',
        checkBox1: 'Adobe Substance 3D',
        checkBox2: 'Adobe Captivate',
        checkBox3: 'Partnerverzeichnis/Distributorverzeichnis',
        checkBox4: 'Angebote',
        checkBox5: 'Erwerb',
        noResultsTitle: 'Keine Ergebnisse gefunden',
      },
    },
    {
      tcid: '16',
      name: '@prp-collection-es-mobile-collection-basics',
      path: '/channelpartners/drafts/automation/regression/prp-collections/prp-collection-all-levels?georouting=off&martech=off',
      tags: '@prp-collection-test @regression @circleCi @mobile',
      data: {
        partnerLevel: 'cpp-spain-platinum:',
        title1: 'PRP Worldwide PPTX',
        title2: 'PRP Europe West JPEG',
        title3: 'PRP EMEA EPS',
        collectionTitle: 'PRP Collection Automation All Levels',
        text1: 'Detail Opcional',
        text2: 'Lorem ipsum odor amet,',
        text3: 'Idioma(s): EN, ES, IT',
        text4: 'Archivos de esta colección',
        expectedURL: '/es/channelpartners/home/marketing/resources/',
      },
    },
    {
      tcid: '17',
      name: '@prp-collection-latam-mobile-filter-open',
      path: '/channelpartners/drafts/automation/regression/prp-collections/prp-collection-all-levels?georouting=off&martech=off',
      tags: '@prp-collection-test @regression @circleCi @mobile',
      data: {
        partnerLevel: 'cpp-latin-america-gold:',
        card1: 'PRP Worldwide PPTX',
        card2: 'PRP Latam MP4',
        filter1: 'Language',
        filter2: 'Type',
        checkBox1: 'Spanish (Latin America)',
        checkBox2: 'Communication, Partner Connect Recording',
        checkBox3: 'Partner Connect Recording',
        checkBox4: 'English Universal (EU)',
        openBtnUrl: 'https://partners.stage.adobe.com/channelpartnerassets/prp-assets/restricted/prp-collection-automation-2026/prp-Latam.mp4',
      },
    },
    {
      tcid: '18',
      name: '@prp-collection-latam-na-mobile-sort-clear',
      path: '/channelpartners/drafts/automation/regression/prp-collections/prp-collection-all-levels?georouting=off&martech=off',
      tags: '@prp-collection-test @regression @circleCi @mobile',
      data: {
        partnerLevel: 'cpp-latin-na-platinum:',
        card1: 'PRP Worldwide PPTX',
        card2: 'PRP Latam NA PNG',
        openBtnUrl: 'https://partners.stage.adobe.com/channelpartnerassets/prp-assets/restricted/prp-collection-automation-2026/prp-LatamNA.png',
        sortOldest: 'Oldest',
        sortNewest: 'Newest',
        filter1: 'Language',
        filter2: 'Type',
        checkBox1: 'Spanish (Latin America)',
        checkBox2: 'Sales Guide',
        noResultsTitle: 'No Results Found',
      },
    },
    {
      tcid: '19',
      name: '@prp-collection-na-mobile-card-basics',
      path: '/channelpartners/drafts/automation/regression/prp-collections/prp-collection-all-levels?georouting=off&martech=off',
      tags: '@prp-collection-test @regression @circleCi @mobile',
      data: {
        partnerLevel: 'cpp-distributor-us:',
        card1: 'PRP Worldwide PPTX',
        card2: 'PRP NA PDF',
        format1: 'pptx',
        format2: 'pdf',
        openBtnUrl: 'https://partners.stage.adobe.com/channelpartnerassets/prp-assets/restricted/prp-collection-automation-2026/prp-NA.pdf',
      },
    },
    {
      tcid: '20',
      name: '@marketing-resources-jp-mobile-resource-load-more',
      path: '/channelpartners/drafts/automation/regression/resources?georouting=off&martech=off',
      tags: '@prp-collection-test @regression @circleCi @mobile',
      data: {
        partnerLevel: 'cpp-distributor-japan:',
        searchKeyword: 'PRP Collection Automation',
      },
    },
    {
      tcid: '21',
      name: '@marketing-resources-emea-mobile-resource-sort',
      path: '/channelpartners/drafts/automation/regression/resources?georouting=off&martech=off',
      tags: '@prp-collection-test @regression @circleCi @mobile',
      data: {
        partnerLevel: 'cpp-emea-platinum:',
        searchKeyword: 'PRP Collection Automation',
        sortOldest: 'Oldest',
        sortNewest: 'Newest',
        oldestTitle1: 'PRP Collection Automation Distributor Platinum Gold',
        oldestTitle2: 'PRP Collection Automation Distributor Platinum PRP Collection Automation Distributor Platinum PRP Collection Automation Distributor Platinum PRP Collection Automation Distributor Platinum PRP Collection Automation Distributor Platinum PRP Collection Automation Distributor Platinum',
        newestTitle1: 'PRP Collection Automation All Levels',
        newestTitle2: 'PRP Collection Automation Distributor Platinum PRP Collection Automation Distributor Platinum PRP Collection Automation Distributor Platinum PRP Collection Automation Distributor Platinum PRP Collection Automation Distributor Platinum PRP Collection Automation Distributor Platinum',
        expectedURL: '/channelpartners/drafts/automation/regression/prp-collections/prp-collection-all-levels',
      },
    },
    {
      tcid: '22',
      name: '@marketing-resources-es-mobile-resource-filters',
      path: '/channelpartners/drafts/automation/regression/resources?georouting=off&martech=off',
      tags: '@prp-collection-test @regression @circleCi @mobile',
      data: {
        partnerLevel: 'cpp-na-certified:',
        searchKeyword: 'PRP Collection Automation',
        title1: 'PRP Collection Automation All Levels',
        language: 'Language(s): EN',
        filter1: 'Product',
        checkBox1: 'Adobe Captivate',
        title2: 'PRP Collection Automation Gold Certified Registered',
        checkBox2: 'Adobe Creative Cloud',
        title3: 'PRP Collection Automation Distributor Certified Registered ŴĦÐŒÞȲŁЖЮҐЩЙЋΨΩΔξβπηさツみロめ愛龍雪火星क्षज्ञअभऋङ한글ㅁㅊㅓㅂعضشقء ל זטכ',
        filter2: 'Topic',
        checkBox3: 'Promotions',
      },
    },
    {
      tcid: '23',
      name: '@marketing-resources-kr-mobile-resource-clear',
      path: '/channelpartners/drafts/automation/regression/resources?georouting=off&martech=off',
      tags: '@prp-collection-test @regression @circleCi @mobile',
      data: {
        partnerLevel: 'cpp-kr-registered:',
        searchKeyword: 'PRP Collection Automation',
        title1: 'PRP Collection Automation All Levels',
        title2: 'PRP Collection Automation Distributor Certified Registered ŴĦÐŒÞȲŁЖЮҐЩЙЋΨΩΔξβπηさツみロめ愛龍雪火星क्षज्ञअभऋङ한글ㅁㅊㅓㅂعضشقء ל זטכ',
        title3: 'PRP Collection Automation Distributor Certified Registered ŴĦÐŒÞȲŁЖЮҐЩЙЋΨΩΔξβπηさツみロめ愛龍雪火星क्षज्ञअभऋङ한글ㅁㅊㅓㅂعضشقء ל זטכ',
        filter1: '제품',
        checkBox1: 'Adobe Express',
        checkBox2: 'Photoshop Elements 및 Premiere Elements 번들',
        filter2: '주제',
        checkBox3: '인센티브',
        checkBox4: '파트너 찾기/총판 찾기',
        noResultsTitle: '검색 결과 없음',
      },
    },

  ],
};
