export default {
  FeatureName: 'DME profile dropdown page',
  features: [
    {
      tcid: '1',
      name: '@desc-profile-dropdown-member-user-with-sales-center',
      path: 'https://partners.stage.adobe.com/channelpartners/?akamaiLocale=na&martech=off',
      tags: '@dme-profile @regression @login @circleCi',
      data: {
        partnerLevel: 'cpp-distributor-apac:',
        profileName: 'Stage CPP Distributor',
        profileEmail: 'yugo-stage-c…@mailinator.com',
        profilePartnerLevel: 'Distributor',
        editProfileURL: 'https://channelpartners.stage2.adobe.com/s/manageprofile/?appid=mp',
        accountManagementURL: 'https://channelpartners.stage2.adobe.com/s/manageprofile/?appid=mp',
        salesCenterURL: 'https://adobe--sfstage.sandbox.my.site.com/',
        targetAfterLogout: 'https://partners.stage.adobe.com/channelpartners/?akamaiLocale=na&martech=off#',
      },
    },
    {
      tcid: '2',
      name: '@desc-profile-dropdown-member-user-with-anniversary-date-next-30-days',
      path: 'https://partners.stage.adobe.com/channelpartners/?akamaiLocale=na&martech=off',
      tags: '@dme-profile @regression @login @circleCi',
      data: {
        partnerLevel: 'cpp-us-registered:',
        profileName: 'CPP Stage Registered Reseller Renew',
        profileEmail: 'yugo-stage-c…@mailinator.com',
        profilePartnerLevel: 'Registered',
        type: 'expired',
        profileRenewText: 'Your account is going to expire soon.',
        editProfileURL: 'https://channelpartners.stage2.adobe.com/s/manageprofile/?appid=mp',
        accountManagementURL: 'https://channelpartners.stage2.adobe.com/s/manageprofile/?appid=mp',
        renewNowURL: 'https://channelpartners.stage2.adobe.com/s/renewal/',
        targetAfterLogout: 'https://partners.stage.adobe.com/channelpartners/?akamaiLocale=na&martech=off#',
      },
    },
    {
      tcid: '3',
      name: '@desc-profile-dropdown-member-user-with-anniversary-date-last-90-days',
      path: 'https://partners.stage.adobe.com/channelpartners/?akamaiLocale=na&martech=off',
      tags: '@dme-profile @regression @login @circleCi',
      data: {
        partnerLevel: 'cpp-us-certified:',
        profileName: 'CPP Stage Reseller Certified',
        profileEmail: 'yugo-stage-c…@mailinator.com',
        profilePartnerLevel: 'Certified',
        type: 'suspended',
        profileRenewText: 'Your account is suspended.',
        editProfileURL: 'https://channelpartners.stage2.adobe.com/s/manageprofile/?appid=mp',
        accountManagementURL: 'https://channelpartners.stage2.adobe.com/s/manageprofile/?appid=mp',
        renewNowURL: 'https://channelpartners.stage2.adobe.com/s/renewal/',
        targetAfterLogout: 'https://partners.stage.adobe.com/channelpartners/?akamaiLocale=na&martech=off#',
      },
    },
  ],
};
