export default {
  FeatureName: 'DME Announcements page',
  features: [
    {
      tcid: '1',
      name: '@desc-regression-announcements-page-search',
      path: '/channelpartners/drafts/automation/regression/announcements?georouting=off&martech=off',
      tags: '@dme-announcements @regression @anonymous @circleCi',
      data: {
        numberOfPublicCards: 7,
        numberOfMatchingDescCards: 6,
        numberOfMatchingTitleCards: 1,
        firstCardTitle: 'Automation regression announcements card worldwide no1',
        secondCardTitle: 'Automation regression announcements card worldwide no2',
        searchCards: 'Automation regression',
      },
    },
    {
      tcid: '2',
      name: '@desc-regression-announcements-page-load-more-sort',
      path: '/channelpartners/drafts/automation/regression/announcements?georouting=off&martech=off',
      tags: '@dme-announcements @regression @anonymous @circleCi',
      data: {
        numberOfPublicCards: 7,
        numberOfMatchingDescCards: 6,
        searchCards: 'Automation regression',
        firstLoadResult: '2 of 6 results',
        secondLoadResult: '4 of 6 results',
        thirdLoadResult: '6 of 6 results',
      },
    },
    {
      tcid: '3',
      name: '@desc-regression-announcements-page-pagination',
      path: '/channelpartners/drafts/automation/regression/announcements-paginated?georouting=off&martech=off',
      tags: '@dme-announcements @regression @anonymous @circleCi',
      data: {
        numberOfPublicCards: 7,
        numberOfMatchingDescCards: 6,
        searchCards: 'Automation regression',
        firstPageResult: '1 - 2 of 6 results',
        secondPageResult: '3 - 4 of 6 results',
        thirdPageResult: '5 - 6 of 6 results',
        pageButtonNumber: 2,
        totalPageCount: 3,
      },
    },
    {
      tcid: '4',
      name: '@desc-regression-announcements-page-filters',
      path: '/channelpartners/drafts/automation/regression/announcements?georouting=off&martech=off',
      tags: '@dme-announcements @regression @anonymous @circleCi',
      data: {
        numberOfPublicCards: 7,
        filterDate: 'Date',
        filterProduct: 'Product',
        filterSales: 'Sales',
        filterMarketing: 'Marketing',
        filterSolutions: 'Solutions',
        filterAdvertising: 'Advertising',
        filterAudience: 'Audience',
        filterPracticeLead: 'Practice Lead',
        filterLastNinetyDays: 'Last 90 days',
        cardsWithSalesAndPracticeLead: 2,
        cardsWithAdvertisingAndSolutions: 2,
        cardsWithAdvertising: 1,
        cardsWithLastNinetyDays: 1,
        cardsWithProduct: 2,
        cardsWithSales: 1,
        titleOfDateFilteredCard: 'Automation regression announcements card Worldwide no4',
        numberOfAudienceFiltersSelected: 2,
      },
    },
    {
      tcid: '5',
      name: '@desc-regression-announcements-page-read-article',
      path: '/channelpartners/drafts/automation/regression/announcements?georouting=off&martech=off',
      tags: '@dme-announcements @regression @anonymous @circleCi',
      data: {
        searchCardTitle: 'Automation regression announcements card worldwide no1',
        numberOfMatchingTitleCards: 1,
        expectedToSeeInURL: '/channelpartners/drafts/automation/regression/cards/cpp-worldwide-no1',
      },
    },
    {
      tcid: '6',
      name: '@desc-announcements-page-edge-cases',
      path: '/channelpartners/drafts/automation/regression/announcements?georouting=off&martech=off',
      tags: '@dme-announcements @regression @anonymous @circleCi',
      data: {
        numberOfPublicCards: 7,
        specialCharsTitleSearch: '? ! | <> * !@#$%^&*()_+~`<>?\\’|”{}][ уљађз',
        cardsWithSpecialChars: 1,
        dateInPastTitleSearch: 'Automation regression announcements card worldwide date in past',
        cardsWithDateInPast: 0,
        eventEndedTitleSearch: 'Automation regression announcements card worldwide event ended',
        cardsWithEventEnded: 0,
        tooLongTitleSearch: 'Automation regression announcements card worldwide too long title',
        cardsWithTooLongTitle: 1,
        noCollectionTagTitleSearch: 'Automation regression announcements card worldwide without collection tag',
        cardsWithoutCollectionTag: 0,
        noTitleSearch: 'Without card title',
        cardsWithoutTitle: 0,
        defaultCardTitle: 'Adobe Partner Connection',
      },
    },
    {
      tcid: '7',
      name: '@desc-regression-logged-in-platinum-user',
      path: '/channelpartners/drafts/automation/regression/announcements?georouting=off&martech=off',
      tags: '@dme-announcements @regression @anonymous',
      data: {
        partnerData: {
          partnerPortal: 'CPP',
          partnerLevel: 'Platinum',
          permissionRegion: 'Europe West',
        },
        partnerLevelCardTitle: 'CPP Platinum Spain Announcement',
        totalNumberOfCards: 10,
        numberOfHigherPartnerLevelCards: 0,
        numberOfMatchingTitleCards: 1,
        numberOfPartnerLevelCards: 1,
      },
    },
    {
      tcid: '8',
      name: '@desc-regression-logged-in-gold-user',
      path: '/channelpartners/drafts/automation/regression/announcements?georouting=off&martech=off',
      tags: '@dme-announcements @regression @anonymous',
      data: {
        partnerData: {
          partnerPortal: 'CPP',
          partnerLevel: 'Gold',
          permissionRegion: 'Latin America',
        },
        higherPartnerLevelCardTitle: 'CPP Platinum Latin America Announcement',
        partnerLevelCardTitle: 'CPP Gold Latin America Announcement',
        totalNumberOfCards: 11,
        numberOfHigherPartnerLevelCards: 0,
        numberOfPartnerLevelCards: 1,
      },
    },
    {
      tcid: '9',
      name: '@desc-regression-logged-in-certified-user',
      path: '/channelpartners/drafts/automation/regression/announcements?georouting=off&martech=off',
      tags: '@dme-announcements @regression @anonymous',
      data: {
        partnerData: {
          partnerPortal: 'CPP',
          partnerLevel: 'Certified',
          permissionRegion: 'Europe East',
        },
        higherPartnerLevelCardTitle: 'CPP Gold Europe East Announcement',
        partnerLevelCardTitle: 'CPP Certified Europe East Announcement',
        totalNumberOfCards: 12,
        numberOfHigherPartnerLevelCards: 0,
        numberOfPartnerLevelCards: 1,
      },
    },
    {
      tcid: '10',
      name: '@desc-regression-logged-in-registered-user',
      path: '/channelpartners/drafts/automation/regression/announcements?georouting=off&martech=off',
      tags: '@dme-announcements @regression @anonymous',
      data: {
        partnerData: {
          partnerPortal: 'CPP',
          partnerLevel: 'Registered',
          permissionRegion: 'China',
        },
        higherPartnerLevelCardTitle: 'CPP Certified China Announcement',
        partnerLevelCardTitle: 'CPP Registered China Announcement',
        totalNumberOfCards: 12,
        numberOfHigherPartnerLevelCards: 0,
        numberOfPartnerLevelCards: 1,
      },
    },
  ],
};
