export default {
  FeatureName: 'DME sign in flow page',
  features: [
    {
      tcid: '1',
      name: '@login-sign-in-sign-out-public-page',
      path: 'https://partners.stage.adobe.com/channelpartners/drafts/automation/regression/public-page?akamaiLocale=na',
      tags: '@dme-signin @regression @login @circleCi',
      data: {
        partnerLevel: 'cpp-spain-platinum:',
        expectedProtectedHomeURL: 'https://partners.stage.adobe.com/channelpartners/drafts/automation/regression/protected-home',
        expectedPublicPageURL: 'https://partners.stage.adobe.com/channelpartners/drafts/automation/regression/public-page',
      },
    },
    {
      tcid: '2',
      name: '@login-accessing-public-home-page-with-member-user-logged-in-to-adobe',
      path: 'https://partners.stage.adobe.com/channelpartners/drafts/automation/regression/public-page?akamaiLocale=na',
      baseURL: 'https://www.stage.adobe.com?akamaiLocale=us',
      tags: '@dme-signin @regression @login @circleCi',
      data: {
        partnerLevel: 'cpp-spain-platinum:',
        expectedToSeeInURL: 'https://partners.stage.adobe.com/channelpartners/drafts/automation/regression/protected-home',
        page: 'public page',
      },
    },
    {
      tcid: '3',
      name: '@login-accessing-restricted-home-page-with-member-user-logged-in-to-adobe',
      path: 'https://partners.stage.adobe.com/channelpartners/drafts/automation/regression/protected-home?akamaiLocale=na',
      baseURL: 'https://www.stage.adobe.com?akamaiLocale=us',
      tags: '@dme-signin @regression @login @circleCi',
      data: {
        partnerLevel: 'cpp-spain-platinum:',
        expectedToSeeInURL: 'https://partners.stage.adobe.com/channelpartners/drafts/automation/regression/protected-home',
        page: 'restricted page',
      },
    },
    {
      tcid: '4',
      name: '@login-direct-sign-in-from-public-home-page-non-member',
      path: 'https://partners.stage.adobe.com/channelpartners/?akamaiLocale=na&martech=off',
      tags: '@dme-signin @regression @login @circleCi',
      data: {
        partnerLevel: 'spp-platinum:',
        expectedRedirectedURL: 'https://partners.stage.adobe.com/channelpartners/error/contact-not-found',
        expectedPublicPageURL: 'https://partners.stage.adobe.com/channelpartners/',
      },
    },
    {
      tcid: '5',
      name: '@login-direct-sign-in-from-program-page-non-member',
      path: 'https://partners.stage.adobe.com/channelpartners/program/?akamaiLocale=na&martech=off',
      tags: '@dme-signin @regression @login @circleCi',
      data: {
        partnerLevel: 'spp-platinum:',
        expectedRedirectedURL: 'https://partners.stage.adobe.com/channelpartners/error/contact-not-found',
        expectedPublicPageURL: 'https://partners.stage.adobe.com/channelpartners/',
      },
    },
    {
      tcid: '6',
      name: '@login-accessing-restricted-home-page-with-non-member-user-logged-in-to-adobe',
      path: 'https://partners.stage.adobe.com/channelpartners/home/?akamaiLocale=na&martech=off',
      baseURL: 'https://www.stage.adobe.com?akamaiLocale=us',
      tags: '@dme-signin @regression @login @circleCi',
      data: {
        partnerLevel: 'tpp-platinum:',
        expectedRedirectedURL: 'https://partners.stage.adobe.com/channelpartners/error/contact-not-found',
        page: 'restricted home',
      },
    },
    {
      tcid: '7',
      name: '@login-accessing-public-page-with-non-member-user-logged-in-to-adobe',
      path: 'https://partners.stage.adobe.com/channelpartners/?akamaiLocale=na&martech=off',
      baseURL: 'https://www.stage.adobe.com?akamaiLocale=us',
      tags: '@dme-signin @regression @login @circleCi',
      data: {
        partnerLevel: 'tpp-platinum:',
        expectedRedirectedURL: 'https://partners.stage.adobe.com/channelpartners/',
        page: 'public page',
      },
    },
    {
      tcid: '8',
      name: '@login-accessing-public-page-and-restricted-home-with-non-member-user-logged-in-to-adobe',
      path: 'https://partners.stage.adobe.com/channelpartners/?akamaiLocale=na&martech=off',
      baseURL: 'https://www.stage.adobe.com?akamaiLocale=us',
      tags: '@dme-signin @regression @login @circleCi',
      data: {
        partnerLevel: 'tpp-platinum:',
        expectedPublicURL: 'https://partners.stage.adobe.com/channelpartners/',
        restrictedHomePath: 'https://partners.stage.adobe.com/channelpartners/home/?akamaiLocale=na&martech=off',
        expectedToSeeInURL: 'https://partners.stage.adobe.com/channelpartners/error/404',
      },
    },
    {
      tcid: '9',
      name: '@login-accessing-restricted-home-with-non-logged-in-user',
      path: 'https://partners.stage.adobe.com/channelpartners/home/?akamaiLocale=na&martech=off',
      tags: '@dme-signin @regression @login @circleCi',
      expectedToSeeInURL: 'https://auth-stg1.services.adobe.com/',
    },
    {
      tcid: '10',
      name: '@login-functionality-with-registered-member-user',
      path: 'https://partners.stage.adobe.com/channelpartners/?akamaiLocale=na&martech=off',
      tags: '@dme-signin @regression @login @circleCi',
      data: { partnerLevel: 'cpp-china-registered:' },
    },
    {
      tcid: '11',
      name: '@login-functionality-with-certified-member-user',
      path: 'https://partners.stage.adobe.com/channelpartners/?akamaiLocale=na&martech=off',
      tags: '@dme-signin @regression @login @circleCi',
      data: { partnerLevel: 'cpp-pacific-certified:' },
    },
    {
      tcid: '12',
      name: '@login-functionality-with-gold-member-user',
      path: 'https://partners.stage.adobe.com/channelpartners/?akamaiLocale=na&martech=off',
      tags: '@dme-signin @regression @login @circleCi',
      data: { partnerLevel: 'cpp-latin-america-gold:' },
    },
    {
      tcid: '13',
      name: '@login-functionality-with-platinum-member-user',
      path: 'https://partners.stage.adobe.com/channelpartners/?akamaiLocale=na&martech=off',
      tags: '@dme-signin @regression @login @circleCi',
      data: { partnerLevel: 'cpp-spain-platinum:' },
    },
    {
      tcid: '14',
      name: '@login-sign-in-sign-out-from-program-page-with-member-user',
      path: 'https://partners.stage.adobe.com/channelpartners/drafts/automation/regression/public-program-page?akamaiLocale=na&martech=off',
      tags: '@dme-signin @regression @login @circleCi',
      data: {
        partnerLevel: 'cpp-latin-america-na-platinum:',
        landingPageAfterLoginURL: 'https://partners.stage.adobe.com/channelpartners/drafts/automation/regression/protected-program-page',
        landingPageAfterLogoutURL: 'https://partners.stage.adobe.com/channelpartners/drafts/automation/regression/public-program-page',
      },
    },
  ],
};
