export default {
  FeatureName: 'DME sign in flow page',
  features: [
    {
      tcid: '1',
      name: '@login-sign-in-sign-out-public-page',
      path: 'https://partners.stage.adobe.com/channelpartners/drafts/automation/regression/public-page?georouting=off',
      tags: '@dme-signin @regression @login @circleCi',
      data: {
        partnerLevel: 'cpp-spain-platinum:',
        expectedProtectedHomeURL: '/es/channelpartners/drafts/automation/regression/protected-home',
        expectedPublicPageURL: '/es/channelpartners/drafts/automation/regression/public-page',
        logoutButtonText: 'Cerrar sesión',
        signInButtonEsGeoText: 'Iniciar sesión',
        signInButtonInternationalText: 'Sign In',
      },
    },
    {
      tcid: '2',
      name: '@login-accessing-public-home-page-with-member-user-logged-in-to-adobe',
      path: 'https://partners.stage.adobe.com/channelpartners/drafts/automation/regression/public-page?georouting=off',
      newTabUrl: 'http://partners.stage.adobe.com/channelpartners/',
      baseURL: 'https://www.stage.adobe.com?akamaiLocale=us',
      tags: '@dme-signin @regression @login @circleCi',
      data: {
        partnerLevel: 'cpp-distributor-us:',
        newTabUrl: 'https://partners.stage.adobe.com/channelpartners/',
        expectedToSeeInURL: 'https://partners.stage.adobe.com/na/channelpartners/home/',
        page: 'public page',
        signInButtonInternationalText: 'Sign In',
      },
    },
    {
      tcid: '3',
      name: '@login-accessing-restricted-home-page-with-member-user-logged-in-to-adobe',
      path: 'https://partners.stage.adobe.com/channelpartners/drafts/automation/regression/protected-home?georouting=off',
      newTabUrl: 'http://partners.stage.adobe.com/channelpartners/',
      baseURL: 'https://www.stage.adobe.com?akamaiLocale=us',
      tags: '@dme-signin @regression @login @circleCi',
      data: {
        partnerLevel: 'cpp-distributor-us:',
        expectedToSeeInURL: 'https://partners.stage.adobe.com/na/channelpartners/home/',
        page: 'restricted page',
        signInButtonInternationalText: 'Sign In',
      },
    },
    {
      tcid: '4',
      name: '@login-direct-sign-in-from-public-home-page-non-member',
      path: 'https://partners.stage.adobe.com/channelpartners/?georouting=off&martech=off',
      tags: '@dme-signin @regression @login @circleCi',
      data: {
        partnerLevel: 'dxp-platinum:',
        expectedRedirectedURL: 'https://partners.stage.adobe.com/channelpartners/error/contact-not-found',
        expectedPublicPageURL: 'https://partners.stage.adobe.com/channelpartners/',
        logoutButtonText: 'Sign Out',
        signInButtonInternationalText: 'Sign In',
        signInButtonText: 'Sign In',
      },
    },
    {
      tcid: '5',
      name: '@login-direct-sign-in-from-program-page-non-member',
      path: 'https://partners.stage.adobe.com/channelpartners/?georouting=off&martech=off',
      tags: '@dme-signin @regression @login @circleCi',
      data: {
        partnerLevel: 'dxp-platinum:',
        expectedRedirectedURL: 'https://partners.stage.adobe.com/channelpartners/error/contact-not-found',
        expectedPublicPageURL: 'https://partners.stage.adobe.com/channelpartners/',
        logoutButtonText: 'Sign Out',
        signInButtonInternationalText: 'Sign In',
        signInButtonText: 'Sign In',
      },
    },
    {
      tcid: '6',
      name: '@login-accessing-restricted-home-page-with-non-member-user-logged-in-to-adobe',
      path: 'https://partners.stage.adobe.com/na/channelpartners/home/?georouting=off&martech=off',
      baseURL: 'http://www.stage.adobe.com?akamaiLocale=us',
      tags: '@dme-signin @regression @login @circleCi',
      data: {
        partnerLevel: 'tpp-platinum:',
        expectedRedirectedURL: 'https://partners.stage.adobe.com/na/channelpartners/error/contact-not-found',
        page: 'restricted home',
        signInButtonText: 'Sign In',
      },
    },
    {
      tcid: '7',
      name: '@login-accessing-public-page-with-non-member-user-logged-in-to-adobe',
      path: 'https://partners.stage.adobe.com/channelpartners/?georouting=off&martech=off',
      baseURL: 'http://www.stage.adobe.com?akamaiLocale=us',
      tags: '@dme-signin @regression @login @circleCi',
      data: {
        partnerLevel: 'tpp-platinum:',
        expectedRedirectedURL: 'https://partners.stage.adobe.com/channelpartners/',
        page: 'public page',
        signInButtonText: 'Sign In',
      },
    },
    {
      tcid: '8',
      name: '@login-accessing-public-page-and-restricted-home-with-non-member-user-logged-in-to-adobe',
      path: 'https://partners.stage.adobe.com/channelpartners/?georouting=off&martech=off',
      baseURL: 'http://www.stage.adobe.com?akamaiLocale=us',
      tags: '@dme-signin @regression @login @circleCi',
      data: {
        partnerLevel: 'tpp-platinum:',
        expectedPublicURL: 'https://partners.stage.adobe.com/channelpartners/',
        restrictedHomePath: 'https://partners.stage.adobe.com/channelpartners/home/?georouting=off&martech=off',
        expectedToSeeInURL: 'https://partners.stage.adobe.com/channelpartners/home/',
        signInButtonText: 'Sign In',
      },
    },
    {
      tcid: '9',
      name: '@login-accessing-restricted-home-with-non-logged-in-user',
      path: 'https://partners.stage.adobe.com/channelpartners/home/?georouting=off&martech=off',
      tags: '@dme-signin @regression @login @circleCi',
      expectedToSeeInURL: 'https://auth-stg1.services.adobe.com/',
      data: { signInButtonText: 'Sign In' },
    },
    {
      tcid: '10',
      name: '@login-functionality-with-registered-member-user',
      path: 'https://partners.stage.adobe.com/channelpartners/?georouting=off&martech=off',
      tags: '@dme-signin @regression @login @circleCi',
      data: {
        partnerLevel: 'cpp-china-registered:',
        signInButtonText: 'Sign In',
      },
    },
    {
      tcid: '11',
      name: '@login-functionality-with-certified-member-user',
      path: 'https://partners.stage.adobe.com/channelpartners/?georouting=off&martech=off',
      tags: '@dme-signin @regression @login @circleCi',
      data: {
        partnerLevel: 'cpp-pacific-certified:',
        signInButtonText: 'Sign In',
      },
    },
    {
      tcid: '12',
      name: '@login-functionality-with-gold-member-user',
      path: 'https://partners.stage.adobe.com/channelpartners/?georouting=off&martech=off',
      tags: '@dme-signin @regression @login @circleCi',
      data: {
        partnerLevel: 'cpp-latin-america-gold:',
        signInButtonText: 'Sign In',
      },
    },
    {
      tcid: '13',
      name: '@login-functionality-with-platinum-member-user',
      path: 'https://partners.stage.adobe.com/channelpartners/?georouting=off&martech=off',
      tags: '@dme-signin @regression @login @circleCi',
      data: {
        partnerLevel: 'cpp-spain-platinum:',
        signInButtonText: 'Sign In',
      },
    },
    {
      tcid: '14',
      name: '@login-sign-in-sign-out-from-program-page-with-member-user',
      path: 'https://partners.stage.adobe.com/channelpartners/drafts/automation/regression/public-program-page?georouting=off&martech=off',
      tags: '@dme-signin @regression @login @circleCi',
      data: {
        partnerLevel: 'cpp-latin-america-na-platinum:',
        landingPageAfterLoginURL: 'https://partners.stage.adobe.com/latam/channelpartners/drafts/automation/regression/protected-program-page',
        landingPageAfterLogoutURL: 'https://partners.stage.adobe.com/latam/channelpartners/drafts/automation/regression/public-program-page',
        logoutButtonText: 'Sign Out',
        signInButtonInternationalText: 'Sign In',
        signInButtonText: 'Sign In', // This will require a change as soon as LA NA based is sorted out
      },
    },
    {
      tcid: '15',
      name: '@login-accessing-public-home-page-access-denied-error',
      path: 'https://partners.stage.adobe.com/channelpartners/drafts/automation/regression/public-page?georouting=off&martech=off',
      tags: '@dme-signin @regression @login @circleCi',
      data: {
        partnerLevel: 'cpp-denied:',
        expectedToSeeInURL: '/channelpartners/error/account-denied',
        signInButtonInternationalText: 'Sign In',
      },
    },
    {
      tcid: '16',
      name: '@login-accessing-public-home-page-account-abandoned-error',
      path: 'https://partners.stage.adobe.com/channelpartners/drafts/automation/regression/public-page?georouting=off&martech=off',
      tags: '@dme-signin @regression @login @circleCi',
      data: {
        partnerLevel: 'cpp-abandoned:',
        expectedToSeeInURL: '/channelpartners/error/login-error',
        signInButtonInternationalText: 'Sign In',
      },
    },
    {
      tcid: '17',
      name: '@login-accessing-public-home-page-account-expired-error',
      path: 'https://partners.stage.adobe.com/channelpartners/drafts/automation/regression/public-page?georouting=off&martech=off',
      tags: '@dme-signin @regression @login @circleCi',
      data: {
        partnerLevel: 'cpp-expired:',
        expectedToSeeInURL: '/channelpartners/error/account-expired',
        signInButtonInternationalText: 'Sign In',
      },
    },
    {
      tcid: '18',
      name: '@login-accessing-view-account-abandoned-user',
      path: 'https://partners.stage.adobe.com/channelpartners/drafts/automation/regression/public-page?georouting=off&martech=off',
      tags: '@dme-signin @regression @login @circleCi',
      data: {
        partnerLevel: 'cpp-abandoned:',
        expectedToSeeInURL: '/channelpartners/error/login-error',
        signInButtonInternationalText: 'Sign In',
        viewAccountButton: 'View Account',
        newTabUrl: 'https://stage.account.adobe.com/?lang=en',
      },
    },
    {
      tcid: '19',
      name: '@verify-na-region-after-login',
      path: 'https://partners.stage.adobe.com/na/channelpartners/?georouting=off&martech=off',
      tags: '@dme-signin @regression @login @circleCi',
      data: {
        partnerLevel: 'cpp-na-certified:',
        signInButtonInternationalText: 'Sign In',
        expectedToSeeInURL: 'https://partners.stage.adobe.com/na/channelpartners/home/?georouting=off&martech=off#',
      },
    },
    {
      tcid: '20',
      name: '@verify-emea-region-after-login',
      path: 'https://partners.stage.adobe.com/emea/channelpartners/?georouting=off&martech=off',
      tags: '@dme-signin @regression @login @circleCi',
      data: {
        partnerLevel: 'cpp-emea-platinum:',
        signInButtonInternationalText: 'Sign In',
        expectedToSeeInURL: 'https://partners.stage.adobe.com/emea/channelpartners/home/?georouting=off&martech=off#',
      },
    },
    {
      tcid: '21',
      name: '@verify-fr-region-after-login',
      path: 'https://partners.stage.adobe.com/fr/channelpartners/?georouting=off&martech=off',
      tags: '@dme-signin @regression @login @circleCi',
      data: {
        partnerLevel: 'cpp-distributor-fr:',
        signInButtonInternationalText: 'Se connecter',
        expectedToSeeInURL: 'https://partners.stage.adobe.com/fr/channelpartners/home/?georouting=off&martech=off#',
      },
    },
    {
      tcid: '22',
      name: '@verify-de-region-after-login',
      path: 'https://partners.stage.adobe.com/de/channelpartners/?georouting=off&martech=off',
      tags: '@dme-signin @regression @login @circleCi',
      data: {
        partnerLevel: 'cpp-de-gold:',
        signInButtonInternationalText: 'Anmelden',
        expectedToSeeInURL: 'https://partners.stage.adobe.com/de/channelpartners/home/?georouting=off&martech=off#',
      },
    },
    {
      tcid: '23',
      name: '@verify-it-region-after-login',
      path: 'https://partners.stage.adobe.com/it/channelpartners/?georouting=off&martech=off',
      tags: '@dme-signin @regression @login @circleCi',
      data: {
        partnerLevel: 'cpp-distributor-it:',
        signInButtonInternationalText: 'Accedi',
        expectedToSeeInURL: 'https://partners.stage.adobe.com/it/channelpartners/home/?georouting=off&martech=off#',
      },
    },
    {
      tcid: '24',
      name: '@verify-es-region-after-login',
      path: 'https://partners.stage.adobe.com/es/channelpartners/?georouting=off&martech=off',
      tags: '@dme-signin @regression @login @circleCi',
      data: {
        partnerLevel: 'cpp-spain-platinum:',
        signInButtonInternationalText: 'Iniciar sesión',
        expectedToSeeInURL: 'https://partners.stage.adobe.com/es/channelpartners/home/?georouting=off&martech=off#',
      },
    },
    {
      tcid: '25',
      name: '@verify-apac-region-after-login',
      path: 'https://partners.stage.adobe.com/apac/channelpartners/?georouting=off&martech=off',
      tags: '@dme-signin @regression @login @circleCi',
      data: {
        partnerLevel: 'cpp-distributor-apac:',
        signInButtonInternationalText: 'Sign In',
        expectedToSeeInURL: 'https://partners.stage.adobe.com/apac/channelpartners/home/?georouting=off&martech=off#',
      },
    },
    {
      tcid: '26',
      name: '@verify-kr-region-after-login',
      path: 'https://partners.stage.adobe.com/kr/channelpartners/?georouting=off&martech=off',
      tags: '@dme-signin @regression @login @circleCi',
      data: {
        partnerLevel: 'cpp-kr-gold:',
        signInButtonInternationalText: '로그인',
        expectedToSeeInURL: 'https://partners.stage.adobe.com/kr/channelpartners/home/?georouting=off&martech=off#',
      },
    },
    {
      tcid: '27',
      name: '@verify-cn-region-after-login',
      path: 'https://partners.stage.adobe.com/cn/channelpartners/?georouting=off&martech=off',
      tags: '@dme-signin @regression @login @circleCi',
      data: {
        partnerLevel: 'cpp-china-registered:',
        signInButtonInternationalText: '登录',
        expectedToSeeInURL: 'https://partners.stage.adobe.com/cn/channelpartners/home/?georouting=off&martech=off#',
      },
    },
    {
      tcid: '28',
      name: '@verify-jp-region-after-login',
      path: 'https://partners.stage.adobe.com/jp/channelpartners/?georouting=off&martech=off',
      tags: '@dme-signin @regression @login @circleCi',
      data: {
        partnerLevel: 'cpp-distributor-japan:',
        signInButtonInternationalText: 'ログイン',
        expectedToSeeInURL: 'https://partners.stage.adobe.com/jp/channelpartners/home/?georouting=off&martech=off#',
      },
    },
    {
      tcid: '29',
      name: '@verify-latam-region-after-login',
      path: 'https://partners.stage.adobe.com/latam/channelpartners/?georouting=off&martech=off',
      tags: '@dme-signin @regression @login @circleCi',
      data: {
        partnerLevel: 'cpp-latin-america-gold:',
        signInButtonInternationalText: 'Sign In',
        expectedToSeeInURL: 'https://partners.stage.adobe.com/latam/channelpartners/home/?georouting=off&martech=off#',
      },
    },
  ],
};
