export default {
  FeatureName: 'DME accessing assets',
  features: [
    {
      tcid: '1',
      name: '@accessing-restricted-asset-non-logged-in-user',
      path: 'https://partners.stage.adobe.com/channelpartnerassets/assets/restricted/restricted_1/MAPC-stage-no-specialization.pptx?download',
      tags: '@dme-accessing-assets @regression @login @circleCi',
      expectedToSeeInURL: 'https://auth-stg1.services.adobe.com/',
    },
    {
      tcid: '2',
      name: '@login-accessing-public-asset-with-member-user-logged-in-to-adobe',
      path: 'https://partners.stage.adobe.com/channelpartners/?georouting=off&martech=off',
      tags: '@dme-accessing-assets @regression @login @circleCi',
      data: {
        partnerLevel: 'cpp-distributor-us:',
        signInButtonText: 'Sign In',
        assetURL: 'https://partners.stage.adobe.com/channelpartnerassets/assets/public/public_1/MAPC_public_stage.pdf',
        httpStatusCode: 200,
      },
    },
    {
      tcid: '3',
      name: '@login-accessing-forbidden-asset-with-member-user-logged-in-to-adobe',
      path: 'https://partners.stage.adobe.com/channelpartners/?georouting=off&martech=off',
      tags: '@dme-accessing-assets @regression @login @circleCi',
      data: {
        partnerLevel: 'cpp-distributor-us:',
        signInButtonText: 'Sign In',
        assetURL: 'https://partners.stage.adobe.com/channelpartnerassets/assets/restricted/restricted_1/MAPC-stage-government.mp4',
        expectedToSeeInURL: '/channelpartners/error/404',
      },
    },
    {
      tcid: '4',
      name: '@login-accessing-asset-with-latam-member-user-logged-in-to-adobe',
      path: 'https://partners.stage.adobe.com/channelpartners/?georouting=off&martech=off',
      tags: '@dme-accessing-assets @regression @login @circleCi',
      data: {
        partnerLevel: 'cpp-latin-na-platinum:',
        signInButtonText: 'Sign In',
        searchText: 'Mexico Reseller Channel Authorization Letter Form',
        expectedAsset: 'Mexico Reseller Channel Authorization Letter Form',
        unwantedAsset: 'MAPC stage education government zip',
        locatorText: 'Mexico Reseller Channel',
        assetURL: '/LATAM_Mexico_Reseller_Authorization_Letter_Form.pdf',
      },
    },
    {
      tcid: '5',
      name: '@login-accessing-asset-with-emea-member-user-logged-in-to-adobe',
      path: 'https://partners.stage.adobe.com/channelpartners/?georouting=off&martech=off',
      tags: '@dme-accessing-assets @regression @login @circleCi',
      data: {
        partnerLevel: 'cpp-uk-gold:',
        signInButtonText: 'Sign In',
        searchText: 'EMEA  Reseller Channel Authorization Form',
        expectedAsset: 'EMEA  Reseller Channel Authorization Form',
        unwantedAsset: 'Mexico Reseller Channel Authorization Letter Form',
        locatorText: 'EMEA Reseller Channel',
        assetURL: 'EMEA_Reseller_Channel_Authorization_Form.pdf',
      },
    },
    {
      tcid: '6',
      name: '@login-accessing-asset-with-na-member-user-logged-in-to-adobe',
      path: 'https://partners.stage.adobe.com/channelpartners/?georouting=off&martech=off',
      tags: '@dme-accessing-assets @regression @login @circleCi',
      data: {
        partnerLevel: 'cpp-distributor-us:',
        signInButtonText: 'Sign In',
        searchText: 'Weights & Measurements for ACRO Acrobat Standard 2020 POSA in BOX',
        expectedAsset: 'Weights & Measurements for ACRO Acrobat Standard 2020 POSA in BOX',
        unwantedAsset: 'Mexico Reseller Channel Authorization Letter Form',
        locatorText: 'Weights & Measurements for ACRO Acrobat Standard 2020 POSA in BOX Last modified',
        assetURL: '/Weights_Measurements_ACRO_AcrobatStandard2020_POSAinBOX.pdf',
      },
    },
    {
      tcid: '7',
      name: '@login-accessing-asset-with-jp-member-user-logged-in-to-adobe',
      path: 'https://partners.stage.adobe.com/channelpartners/?georouting=off&martech=off',
      tags: '@dme-accessing-assets @regression @login @circleCi',
      data: {
        partnerLevel: 'cpp-distributor-japan:',
        signInButtonText: 'Sign In',
        searchText: 'MAPC Test asset (Japan Only)QA',
        expectedAsset: 'MAPC Test asset (Japan Only) QA',
        unwantedAsset: 'Mexico Reseller Channel Authorization Letter Form',
        locatorText: 'MAPC Test asset (Japan Only)',
        assetURL: '/japan-gold.pdf',
      },
    },
    {
      tcid: '8',
      name: '@login-accessing-asset-with-cn-member-user-logged-in-to-adobe',
      path: 'https://partners.stage.adobe.com/channelpartners/?georouting=off&martech=off',
      tags: '@dme-accessing-assets @regression @login @circleCi',
      data: {
        partnerLevel: 'cpp-platinum-china:',
        signInButtonText: 'Sign In',
        searchText: 'China Reseller Channel authorization application form',
        expectedAsset: 'China Reseller Channel authorization application form',
        unwantedAsset: 'EMEA  Reseller Channel Authorization Form',
        locatorText: 'China Reseller Channel',
        assetURL: '/China_Reseller_CAL_form.pdf',
      },
    },
    {
      tcid: '9',
      name: '@login-accessing-asset-with-kr-member-user-logged-in-to-adobe',
      path: 'https://partners.stage.adobe.com/channelpartners/?georouting=off&martech=off',
      tags: '@dme-accessing-assets @regression @login @circleCi',
      data: {
        partnerLevel: 'cpp-kr-gold:',
        signInButtonText: 'Sign In',
        searchText: 'MAPC Test Asset (Korea Only) QA',
        expectedAsset: 'MAPC Test Asset (Korea) QA',
        unwantedAsset: 'MAPC Test asset (Japan Only) QA',
        locatorText: 'MAPC Test Asset (Korea) QA',
        assetURL: '/korea-gold.pdf',
      },
    },
  ],
};
