export default {
  FeatureName: 'DME redirections flow',
  features: [
    {
      tcid: '1',
      name: '@verify-find-partner-redirections',
      path: '/channelpartners/#?georouting=off&martech=off',
      tags: '@dme-redirections @regression @circleCi',
      data: {
        findPartnerLinkText: 'Find a Partner',
        findPartnerFrenchLinkText: 'Trouver un partenaire',
        findPartnerGermanLinkText: 'Adobe-Partner suchen',
        findPartnerItalianLinkText: 'Trova un partner',
        findPartnerSpanishLinkText: 'Encontrar un partner',
        findPartnerKorianLinkText: '파트너 찾기',
        findPartnerChinaLinkText: '查找合作伙伴',
        findPartnerJapanLinkText: 'パートナーを見つける',
        naLocalePartnerUrl: 'https://adobe.my.salesforce-sites.com/PartnerSearch?lang=en',
        frLocalePartnerUrl: 'https://adobe--sfstage1.sandbox.my.salesforce-sites.com/PartnerSearch?lang=fr',
        deLocalePartnerUrl: 'https://adobe.my.salesforce-sites.com/PartnerSearch?lang=de',
        itLocalePartnerUrl: 'https://adobe--sfstage1.sandbox.my.salesforce-sites.com/PartnerSearch?lang=it',
        esLocalePartnerUrl: 'https://adobe--sfstage1.sandbox.my.salesforce-sites.com/PartnerSearch?lang=es',
        krLocalePartnerUrl: 'https://adobe--sfstage1.sandbox.my.salesforce-sites.com/PartnerSearch?lang=ko',
        cnLocalePartnerUrl: 'https://adobe--sfstage1.sandbox.my.salesforce-sites.com/PartnerSearch?lang=zh_CN',
        jpLocalePartnerUrl: 'https://adobe.my.salesforce-sites.com/PartnerSearch?lang=ja',
        naLocaleSwitchUrl: '/na/channelpartners/#?georouting=off&martech=off',
        latamLocaleSwitchUrl: '/latam/channelpartners/#?georouting=off&martech=off',
        emeaLocaleSwitchUrl: '/emea/channelpartners/#?georouting=off&martech=off',
        frLocaleSwitchUrl: '/fr/channelpartners/#?georouting=off&martech=off',
        deLocaleSwitchUrl: '/de/channelpartners/#?georouting=off&martech=off',
        itLocaleSwitchUrl: '/it/channelpartners/#?georouting=off&martech=off',
        esLocaleSwitchUrl: '/es/channelpartners/#?georouting=off&martech=off',
        apacLocaleSwitchUrl: '/apac/channelpartners/#?georouting=off&martech=off',
        krLocaleSwitchUrl: '/kr/channelpartners/#?georouting=off&martech=off',
        cnLocaleSwitchUrl: '/cn/channelpartners/#?georouting=off&martech=off',
        jpLocaleSwitchUrl: '/jp/channelpartners/#?georouting=off&martech=off',
      },
    },
  ],
};
