name: DME-Partners Nala Tests

on:
  pull_request:
    types: [ labeled, synchronize, reopened ]

jobs:
  action:
    name: Running E2E & IT
    if: github.event.label.name == 'run-on-dme'
      || (github.event.action == 'synchronize' && contains(join(github.event.pull_request.labels.*.name, ','), 'run-on-dme'))
      || (github.event.action =='reopened' && contains(join(github.event.pull_request.labels.*.name, ','), 'run-on-dme'))
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Run Nala
        uses: adobecom/dme-partners@stage # Change if doing dev work
        env:
          labels: ${{ '@anonymous' }}
          branch: ${{ github.event.pull_request.head.ref }}
          repoName: ${{ github.repository }}
          prUrl: ${{ github.event.pull_request.head.repo.html_url }}
          prOrg: ${{ github.event.pull_request.head.repo.owner.login }}
          prRepo: ${{ github.event.pull_request.head.repo.name }}
          prBranch: ${{ github.event.pull_request.head.ref }}
          prBaseBranch: ${{ github.event.pull_request.base.ref }}
          IMS_EMAIL: ${{ secrets.IMS_EMAIL }}
          IMS_PASS: ${{ secrets.IMS_PASS }}
          HLX_API_KEY: ${{ secrets.HLX_API_KEY }}
